export const liveState = {
  markets: {
    41171117: {
      marketId: 41171117,
      eventId: 3962053,
      name: "Full Time Result",
      type: "standard",
      displayOrder: 1,
      displayStatus: "active",
      ewAvailable: false,
      notes: {
        essential: [],
        promo: [],
      },
      cashoutable: true,
      outcomes: ["174702066", "174702067", "174702070"],
      openByDefault: true,
    },
    41171120: {
      marketId: 41171120,
      eventId: 3962053,
      name: "Both Teams To Score",
      type: "standard",
      displayOrder: 1,
      displayStatus: "active",
      ewAvailable: false,
      notes: {
        essential: [],
        promo: [],
      },
      cashoutable: true,
      outcomes: ["174702074", "174702073"],
      openByDefault: true,
    },
    41171121: {
      marketId: 41171121,
      eventId: 3962053,
      name: "Bookings",
      type: "standard",
      displayOrder: 1,
      displayStatus: "active",
      ewAvailable: false,
      notes: {
        essential: [],
        promo: [],
      },
      cashoutable: false,
      outcomes: ["174702075"],
      openByDefault: true,
    },
    41171123: {
      marketId: 41171123,
      eventId: 3962053,
      name: "Super Boost",
      type: "super-boost",
      displayOrder: 1,
      displayStatus: "active",
      ewAvailable: false,
      notes: {
        essential: [],
        promo: [],
      },
      cashoutable: true,
      outcomes: ["174702079"],
      openByDefault: true,
    },
  },
  outcomes: {
    174702066: {
      displayOrder: 10,
      name: "Hazaribag United",
      suspended: false,
      outcomeId: 174702066,
      marketId: 41171117,
      eventId: 3962053,
      displayStatus: "active",
      boosted: false,
      price: {
        num: 10,
        den: 1,
      },
      fbResult: "H",
      cashoutable: true,
      selected: false,
    },
    174702067: {
      displayOrder: 20,
      name: "Draw",
      suspended: false,
      outcomeId: 174702067,
      marketId: 41171117,
      eventId: 3962053,
      displayStatus: "active",
      boosted: false,
      price: {
        num: 9,
        den: 4,
      },
      fbResult: "D",
      cashoutable: true,
      selected: false,
    },
    174702070: {
      displayOrder: 30,
      name: "Lalganj Argyle",
      suspended: false,
      outcomeId: 174702070,
      marketId: 41171117,
      eventId: 3962053,
      displayStatus: "active",
      boosted: false,
      price: {
        num: 15,
        den: 1,
      },
      fbResult: "A",
      cashoutable: true,
      selected: false,
    },
    174702073: {
      displayOrder: 10,
      name: "Yes",
      suspended: false,
      outcomeId: 174702073,
      marketId: 41171120,
      eventId: 3962053,
      displayStatus: "active",
      boosted: false,
      price: {
        num: 1,
        den: 1,
      },
      fbResult: "-",
      cashoutable: true,
      selected: false,
    },
    174702074: {
      displayOrder: 10,
      name: "No",
      suspended: false,
      outcomeId: 174702074,
      marketId: 41171120,
      eventId: 3962053,
      displayStatus: "active",
      boosted: false,
      price: {
        num: 1,
        den: 1,
      },
      fbResult: "-",
      cashoutable: true,
      selected: false,
    },
    174702075: {
      displayOrder: 10,
      name: "Under 60 match booking points",
      suspended: false,
      outcomeId: 174702075,
      marketId: 41171121,
      eventId: 3962053,
      displayStatus: "active",
      boosted: false,
      price: {
        num: 1,
        den: 1,
      },
      fbResult: "-",
      cashoutable: false,
      selected: false,
    },
    174702079: {
      displayOrder: 10,
      name: "Hazaribag United to Win 2-1",
      suspended: false,
      outcomeId: 174702079,
      marketId: 41171123,
      eventId: 3962053,
      displayStatus: "active",
      boosted: true,
      price: {
        num: 15,
        den: 1,
      },
      fbResult: "-",
      cashoutable: true,
      superBoost: {
        was: {
          num: 10,
          den: 1,
        },
        boost: {
          num: 15,
          den: 1,
        },
      },
      selected: false,
    },
  },
  ui: {
    selectedMarketGroup: "All Markets",
    marketGroups: ["All Markets", "Cash Out", "Team", "Cards"],
    "footballAccordion.openMarkets": {
      41171117: true,
      41171120: true,
      41171121: true,
      41171123: true,
    },
    isMobileDevice: false,
    favouriteMarkets: [],
  },
  filters: {
    open: false,
    "RequestABet Markets": [
      {
        name: "Team to win",
        applied: false,
      },
      {
        name: "To Score",
        applied: false,
      },
      {
        name: "Player carded",
        applied: false,
      },
      {
        name: "Correct Score",
        applied: false,
      },
      {
        name: "Both Teams To Score - Yes or No",
        applied: false,
      },
      {
        name: "Over/Under Goals",
        applied: false,
      },
      {
        name: "Bookings",
        applied: false,
      },
      {
        name: "Corners",
        applied: false,
      },
    ],
    "All Markets": [
      {
        name: "Team to win",
        applied: false,
      },
      {
        name: "To Score",
        applied: false,
      },
      {
        name: "Player carded",
        applied: false,
      },
      {
        name: "Correct Score",
        applied: false,
      },
      {
        name: "Both Teams To Score - Yes or No",
        applied: false,
      },
      {
        name: "Over/Under Goals",
        applied: false,
      },
      {
        name: "Bookings",
        applied: false,
      },
      {
        name: "Corners",
        applied: false,
      },
    ],
  },
  rab: {
    enabled: false,
    loading: false,
    orderedSelections: [],
    requested: false,
    selectionsCount: 0,
    matched: false,
    myRabMarketOpen: false,
    selections: {
      41171117: {
        open: false,
        selections: [],
        limit: 1,
        sortOrder: 6,
      },
      41171120: {
        open: false,
        selections: [],
        limit: 1,
        sortOrder: 7,
      },
      41171121: {
        open: false,
        selections: [],
        limit: 1,
        sortOrder: 4,
      },
    },
    suggestions: [],
    myRabMap: {},
  },
  scorecast: {},
  appConfig: {
    filtersEnabled: false,
    filtersV2Enabled: true,
    surveyEnabled: false,
    oneBetAccordions: true,
    rabSuggestionLimit: 4,
    priceFormat: "Odds",
    nexusRab: false,
    betRabApiUrl: "https://rab.test4.betviewapi.com",
    nexusRabFreeBets: false,
    nexusRabAdditionalMarkets: false,
    showFavouriteMarkets: true,
    createARabBehindTab: true,
    promoUnderOver: true,
    footballSearchWithinMarket: false,
    hideMarketNotes: false,
    statsOnMarkets: false,
    rabButtonStyleUpdate: false,
    eventNotesInHeader: true,
    eventEndpointUrl: "https://events.test-aws.test4.skybet.com/graphql",
    accaPrompt: false,
    showBabEntryPoint: false,
    module: "Football - Event-Page",
  },
  meta: {
    classId: 5,
    className: "football",
    eventHasRequestABet: false,
    userLoggedIn: false,
    isLive: false,
    eventId: 3962053,
    eventName: "Hazaribag United v Lalganj Argyle",
    eventStart: "1719527639000",
    eventNotes: {
      essential: "",
      promo: "",
    },
    typeId: 1,
    affiliateId: null,
    clientName: "gen_webih",
  },
  balance: {
    currency: "£",
    value: null,
  },
};
